# Generated by Django 4.2.2 on 2023-06-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_video_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('user', models.CharField(max_length=80, verbose_name='user')),
                ('photo', models.TextField(default='SOME STRING', verbose_name='photo')),
                ('date', models.TextField(default='YYYY-MM-DD', verbose_name='date')),
                ('video', models.TextField(default='SOME STRING', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='table_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='user', verbose_name='text')),
                ('email', models.TextField(default='email', verbose_name='models')),
                ('password', models.TextField(default='password', verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='video_page_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', models.TextField(default='link', verbose_name='main_video')),
                ('video_1', models.TextField(default='link', verbose_name='video1')),
                ('video_2', models.TextField(default='link', verbose_name='video2')),
                ('video_3', models.TextField(default='link', verbose_name='video3')),
                ('video_4', models.TextField(default='link', verbose_name='video4')),
                ('video_5', models.TextField(default='link', verbose_name='video5')),
            ],
        ),
    ]
