# Generated by Django 4.2.2 on 2023-06-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_user',
            name='email',
            field=models.TextField(default='email', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='table_user',
            name='usuario',
            field=models.TextField(default='user', verbose_name='usuario'),
        ),
    ]
