# Generated by Django 4.2.2 on 2023-06-13 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_alter_table_user_email_alter_table_user_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_page_links',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
