# Generated by Django 4.2.2 on 2023-06-13 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_video_page_links_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_page_links',
            name='likes',
        ),
        migrations.AddField(
            model_name='home_video_links',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
